:data-uri:
:toc2:

:numbered!:
:ref_arch_doc: link:doc/ref_arch.adoc[here]

== PURPOSE:
* Discuss use-cases for integration between Red Hat Fuse Service Works (FSW) and BPM Suite 6
* Demonstrate integration of FSW and BPM Suite 6 using REST APIs
* Provide harness to drive load-testing of integration layer between FSW and BPM Suite 6

== OVERVIEW:
The focus of this reference architecture is on the integration of FSW and BPM Suite 6 using REST APIs.
For the purposes of this reference architecture, the target run-time environments are OpenShift gears enabled with FSW and BPM Suite 6.  With minimal changes, this reference architecture could also be applied to a non-PaaS environment.

This reference architecture includes the following manual:  doc/ref_arch.adoc .
This reference architecture also includes both client and server-side source code to a scenario called
_policyQuote_.  This _policyQuote_ scenario is referenced throughout the manual for this reference
architecture.

== DETAILS:
Complete documentation for this reference architecture can be found {ref_arch_doc}.
