=== instructions:
  1)  mvn clean install
  2)  local :   cp -r domain/conf/com $JBOSS_HOME/modules/system/layers/base
    
      remote:   ssh <ssh_url_to_your_openshift_environment> 'mkdir -p app-root/data/appModules'
                scp -r domain/conf/com <ssh_url_to_your_openshift_environment>:~/app-root/data/appModules/
  3)  local :   cp domain/target/domain-1.0.jar $JBOSS_HOME/modules/system/layers/base/com/redhat/gpe/refarch/fsw_bpms_integration/domain/main
      remote:   scp domain/target/domain-1.0.jar    <ssh_url_to_your_openshift_environment>:~/app-root/data/appModules/com/redhat/gpe/refarch/fsw_bpms_integration/domain/main/
  4)  add an explicit dependency on this static module

        ....
        <dependencies>
            <module name="com.redhat.gpe.refarch.fsw_bpms_integration.domain" export="true"/>
        </dependencies
        ...

  5)  bounce the JBoss EAP/BPMS JVM :   ctl_app restart  (select option 1. bpms-6.0)

=== transaction boundaries

=== To-Do
* send policy object as payload of startProcess POST
* specify processId to start as per the message payload to this component
* specify role used to query for potential tasks
* identify tasks that have already been claimed and iterate to next task in NodeList
* demonstrate invocation of the following BPM Suite 6 task operation:  claimnextavailable
* error handling when substitution properties in URL of REST invocation are not valid
** currently rolls back outside of scope of ProcessMgmtBean
** causes multiple invocations of startProcess call)

